import re
from datetime import datetime
from pathlib import Path

SESSION_LOGS_DIR = Path(".context/memories/session_logs")
OUTPUT_FILE = SESSION_LOGS_DIR / "meta_summary.md"


def parse_session_log(file_path):
    content = file_path.read_text(encoding="utf-8")

    # Extract Session ID and Date from filename or content
    stem = file_path.stem
    # Expecting format: YYYY-MM-DD-session-XX.md or similar
    # But file says "2026-01-30-session-04.md"

    session_id = "Unknown"
    date_str = "Unknown"

    match_filename = re.search(r"(\d{4}-\d{2}-\d{2})-session-(\d+)", stem)
    if match_filename:
        date_str = match_filename.group(1)
        session_id = match_filename.group(2)

    # Extract "Verdict"
    verdict = "N/A"
    verdict_match = re.search(r"\*\*Verdict\*\*: (.*)", content)
    if verdict_match:
        verdict = verdict_match.group(1).strip()

    # Extract Summary from Checkpoint
    summary = "No summary found."
    summary_match = re.search(r"\*\*Summary\*\*: (.*)", content)
    if summary_match:
        summary = summary_match.group(1).strip()
    else:
        # Fallback to finding "Goal" or "Focus"
        focus_match = re.search(r"\*\*Focus\*\*: (.*)", content)
        if focus_match:
            summary = f"(Focus) {focus_match.group(1).strip()}"

    return {
        "date": date_str,
        "session": session_id,
        "verdict": verdict,
        "summary": summary,
        "filename": file_path.name,
    }


def main():
    if not SESSION_LOGS_DIR.exists():
        print(f"Directory not found: {SESSION_LOGS_DIR}")
        return

    logs = []
    print(f"Scanning {SESSION_LOGS_DIR}...")

    for file_path in SESSION_LOGS_DIR.glob("*.md"):
        if file_path.name == "meta_summary.md":
            continue
        try:
            log_data = parse_session_log(file_path)
            logs.append(log_data)
        except Exception as e:
            print(f"Error parsing {file_path.name}: {e}")

    # Sort by date/session (descending)
    logs.sort(key=lambda x: (x["date"], x["session"]), reverse=True)

    # Generate Markdown
    md_content = "# Session Memory Index\n\n"
    md_content += "**Generated by:** Nurse Clawbot 🦞\n"
    md_content += f"**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
    md_content += "| Date | Session | Verdict | Summary |\n"
    md_content += "|------|---------|---------|---------|\n"

    for log in logs:
        link = f"[{log['session']}]({log['filename']})"
        # Sanitize pipes in summary to avoid breaking table
        safe_verdict = log["verdict"].replace("|", "/")
        safe_summary = log["summary"].replace("|", "/")
        md_content += f"| {log['date']} | {link} | {safe_verdict} | {safe_summary} |\n"

    OUTPUT_FILE.write_text(md_content, encoding="utf-8")
    print(f"✅ Generated meta_summary.md with {len(logs)} entries.")


if __name__ == "__main__":
    main()
